# Generated by Django 3.2.7 on 2021-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('mac', models.CharField(max_length=64)),
            ],
        ),
    ]
