# Generated by Django 3.2.7 on 2021-10-01 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portalweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiempo',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
