# Generated by Django 3.2.7 on 2021-10-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalweb', '0002_usuario_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tiempo',
            field=models.CharField(max_length=64),
        ),
    ]
