# Generated by Django 3.2.7 on 2021-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalweb', '0003_alter_usuario_tiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
