# Generated by Django 3.2.7 on 2021-10-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portalweb', '0004_vip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VIP',
            new_name='Vips',
        ),
    ]
