# Generated by Django 3.2.7 on 2021-10-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portalweb', '0005_rename_vip_vips'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
